---
keys:
  - &sillock 400670D8EC65A6C34626665F16D2392AC3023DC3
  - &deimos age1k689d3xa2dwkdrrwxyhk47vnuy7849fxvh73m0q88snhxcsmgqas9ls5v8
  - &desktop-vm age13vw6x8lf405njpvghajj3jmtd7d0gycgrpzexgsym6066tuyk37qydzput
  - &server-vm age1ntsfvgs6ydtnrhtnm9wpt8vkxtjpls36lw4xugslxw27yt8fsfuq4s0azq

creation_rules:
  - path_regex: .*\.sops\.ya?ml$
    key_groups:
      - age:
          - *deimos
          - *desktop-vm
          - *server-vm
        pgp:
          - *sillock