---
keys:
  - &sillock 5922765DA44FED87F98EE2FBA4572BEA3D629397
  - &deimos age1hlaqj4alvqdc4cl5cfaltdnyua5u8va80rmstgn4sd3ez7xyjv3smx2p2j
  - &desktop-vm age1e5lelu0ezhwx5etzfqk8e5savlp4x9vxm2mj5hfz5l34sf3v94gsgyq224
  - &server-vm age1ntsfvgs6ydtnrhtnm9wpt8vkxtjpls36lw4xugslxw27yt8fsfuq4s0azq
  - &luna age1u7wsy98kx5q28ch7kfq0jsxvq09qjsh9nqs7m360mr35ys8wlsjq76p3h8
  - &sgr age18ju608xtjfeftrn6wv6dhpwzz7nl923vfj07a65sp8lcunn7c56sawhmkg

creation_rules:
  - path_regex: .*\.sops\.ya?ml$
    key_groups:
      - age:
          - *deimos
          - *desktop-vm
          - *server-vm
          - *luna
          - *sgr
        pgp:
          - *sillock
