---
keys:
  - &sillock 400670D8EC65A6C34626665F16D2392AC3023DC3
  - &deimos age1hlaqj4alvqdc4cl5cfaltdnyua5u8va80rmstgn4sd3ez7xyjv3smx2p2j
  - &desktop-vm age1e5lelu0ezhwx5etzfqk8e5savlp4x9vxm2mj5hfz5l34sf3v94gsgyq224
  - &server-vm age1ntsfvgs6ydtnrhtnm9wpt8vkxtjpls36lw4xugslxw27yt8fsfuq4s0azq

creation_rules:
  - path_regex: .*\.sops\.ya?ml$
    key_groups:
      - age:
          - *deimos
          - *desktop-vm
          - *server-vm
        pgp:
          - *sillock