---
keys:
  - &sillock 400670D8EC65A6C34626665F16D2392AC3023DC3
  - &desktop-vm age17g69vqw92knjxc3vernzl7vjd7atqc697s8qjnyf2pfuts2eycvqrfr2u5
  - &server-vm age1ntsfvgs6ydtnrhtnm9wpt8vkxtjpls36lw4xugslxw27yt8fsfuq4s0azq

creation_rules:
  - path_regex: .*\.sops\.ya?ml$
    key_groups:
      - age:
          - *desktop-vm
          - *server-vm
        pgp:
          - *sillock