---
version: "3"

tasks:
  apply-local:
    desc: Build and apply nix configuration to a local machine
    silent: true
    summary: |
      Args:
        host: Host to build and deploy to (required)
    requires:
      vars:
        - host
    cmds:
      - task: build-local
        vars:
          host: "{{ .host }}"
      - task: .prompt_to_continue
      - nixos-rebuild switch --flake "{{.ROOT_DIR}}/#{{.host}}"
    preconditions:
      - sh: which nix
        msg: "nix not found"
      - sh: which nixos-rebuild
        msg: "nixos-rebuild not found"

  build-local:
    desc: Build local nix configuration
    silent: true
    summary: |
      Args:
        host: Host to build and deploy to (required)
    requires:
      vars:
        - host
    cmds:
      - nixos-rebuild build --flake "{{.ROOT_DIR}}/#{{.host}}"
      - nvd diff /run/current-system result
    preconditions:
      - sh: which nix
        msg: "nix not found"
      - sh: which nixos-rebuild
        msg: "nixos-rebuild not found"

  apply-remote:
    desc: Build and deploy nixos configuration using deploy-rs to a remote machine
    silent: true
    summary: |
      Args:
        host: Host to build and deploy to (required)
    requires:
      vars:
        - host
    cmds:
      - deploy "{{.ROOT_DIR}}/#{{.host}}" --interactive --skip-checks
    preconditions:
      - sh: which nix
        msg: "nix not found"
      - sh: which deploy
        msg: "deploy-rs not found"

  .prompt_to_continue:
    internal: true
    prompt: Do you want to continue applying this configuration?